AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 'Hourly IESO Data Fetcher'

Resources:
  hourlydatafetch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: 'Hourly IESO fetcher'
      MemorySize: 128
      Timeout: 30                     # give a bit more time than 20s
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Environment:
        Variables:
          S3_BUCKET: "energy-forecast-nishan"
          S3_PREFIX: "hourly_data/"
      Policies:
        - Statement:
            - Sid: S3AccessForPipeline
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - arn:aws:s3:::energy-forecast-nishan
                - arn:aws:s3:::energy-forecast-nishan/*
      Events:
        HourlySchedule:
          Type: Schedule
          Properties:
            Schedule: "rate(1 hour)"    # runs every hour
            Enabled: True